#!/usr/bin/env python3
"""Generate the V5 integration backlog.

Enforces the project's screening rules directly, so the backlog can never again
include offline work or ignored technical reports:

  1. Three conditions are the ONLY criterion. `is_opd=analysis` is not a pass.
     Reject if student rollouts are absent, or rollout_frequency is off-policy.
  2. Technical reports are ignored unless they carry an OPD method contribution.
  3. Papers already cited in the V5 bib are done, not backlog.
"""

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path("/apdcephfs_cq8/share_1324356/nickmysong/daily_research/on-policy-distillation-survey")
OFF_POLICY_FREQS = {"once-before-training", "n/a", "none", "offline", "once"}

# Ruled out 2026-08-12: technical reports without an OPD method contribution.
TECH_REPORT_IGNORE = {
    "2606.31984": "GR2 Technical Report",
    "2607.05471": "KAT-Coder-V2.5 Technical Report",
    "2607.09375": "Mach-Mind-4-Flash Technical Report",
    "2607.13639": "OvisOCR2 Technical Report",
    "2607.20062": "Solar Open 2 Technical Report",
    "2607.24653": "Kimi K3: Open Frontier Intelligence",
    "2608.06756": "Capek 0.5",
    "2608.09119": "Motif 3: Technical Report",
}

SECTION_ORDER = [
    "§4.1", "§4.2", "§4.3",
    "§5.1", "§5.1.1", "§5.1.2", "§5.2", "§5.2.1", "§5.2.2",
    "§5.3.1", "§5.3.2", "§5.3.3",
    "§6.1", "§6.2", "§6.3",
    "§7.1", "§7.2",
    "§8.1", "§8.2",
]


def load_notes():
    return json.loads((ROOT / "notes/paper_notes.json").read_text())["notes"]


def bib_ids(*paths):
    ids = set()
    for p in paths:
        f = ROOT / p
        if f.exists():
            ids |= set(re.findall(r"(\d{4}\.\d{4,5})", f.read_text(errors="ignore")))
    return ids


def condition_1(mech):
    """Student rollouts during training. None means the field is missing."""
    explicit = mech.get("student_rollout_in_training")
    if explicit is not None:
        return explicit == "yes"
    source = (mech.get("rollout_source") or "").lower()
    if source:
        return any(k in source for k in ("student", "self", "policy"))
    return None


def passes_three_conditions(rec):
    mech = rec.get("on_policy_mechanism", {}) or {}
    if condition_1(mech) is False:
        return False
    if (mech.get("rollout_frequency") or "").lower() in OFF_POLICY_FREQS:
        return False
    return True


def main():
    notes = load_notes()
    v4 = bib_ids("latex-v4/references.bib", "latex-v4/references_background.bib")
    v5 = bib_ids("latex-v5/references.bib", "latex-v5/references_background.bib")
    awesome = set(re.findall(
        r"(\d{4}\.\d{4,5})",
        (ROOT / "Awesome-LLM-On-Policy-Distillation/README.md").read_text(errors="ignore"),
    ))

    eligible, rejected_3c = [], []
    for aid, rec in notes.items():
        if not re.fullmatch(r"\d{4}\.\d{4,5}", aid):
            continue
        if ((rec.get("opd_classification", {}) or {}).get("is_opd") or "").lower() not in ("yes", "analysis"):
            continue
        (eligible if passes_three_conditions(rec) else rejected_3c).append(aid)

    pending = sorted(a for a in eligible if a not in v5 and a not in TECH_REPORT_IGNORE)
    ignored = sorted(a for a in eligible if a not in v5 and a in TECH_REPORT_IGNORE)

    def cls(aid):
        return notes[aid].get("opd_classification", {}) or {}

    groups = defaultdict(list)
    for aid in pending:
        groups[str(cls(aid).get("primary_section"))].append(aid)

    out = []
    w = out.append
    w("# V5 Integration Backlog — deep-read after V4, not yet cited")
    w("")
    w("> Generated by `scripts/generate_v5_backlog.py`. Source of truth: `notes/paper_notes.json`.")
    w("> Three conditions are enforced in code; `is_opd=analysis` alone is **not** a pass.")
    w("")
    w("## Summary")
    w("")
    w("| Metric | Count |")
    w("|---|---:|")
    w(f"| DB records | {len(notes)} |")
    w(f"| Pass three conditions | {len(eligible)} |")
    w(f"| Cited in V4 bib | {len(v4)} |")
    w(f"| Cited in V5 bib | {len(v5)} |")
    w(f"| **Pending V5 integration** | **{len(pending)}** |")
    w(f"| Technical reports ignored by rule | {len(ignored)} |")
    w(f"| Awesome README entries | {len(awesome)} |")
    w("")
    months = Counter(a[:4] for a in pending)
    w("Pending by arXiv month: " + ", ".join(f"`{k}`={v}" for k, v in sorted(months.items())))
    w("")
    kinds = Counter((cls(a).get("is_opd") or "").lower() for a in pending)
    w(f"Backlog split: **{kinds.get('yes', 0)} method**, {kinds.get('analysis', 0)} analysis.")
    w("")
    w("## Pending papers by target section")
    for sec in SECTION_ORDER + sorted(set(groups) - set(SECTION_ORDER)):
        if sec not in groups:
            continue
        ids = sorted(groups[sec])
        w("")
        w(f"### {sec} — {len(ids)} papers")
        w("")
        w("| arXiv | OPD | In Awesome | Title |")
        w("|---|---|---|---|")
        for aid in ids:
            mark = "yes" if aid in awesome else "no (analysis-only, by policy)"
            title = (notes[aid].get("title") or "").replace("|", "/")[:88]
            w(f"| `{aid}` | {(cls(aid).get('is_opd') or '').lower()} | {mark} | {title} |")

    w("")
    w("## Ignored by rule — technical reports without an OPD method contribution")
    w("")
    w("| arXiv | Name |")
    w("|---|---|")
    for aid in ignored:
        w(f"| `{aid}` | {TECH_REPORT_IGNORE[aid]} |")

    w("")
    w("## Excluded by three-condition enforcement")
    w("")
    if rejected_3c:
        w("| arXiv | Title |")
        w("|---|---|")
        for aid in sorted(rejected_3c):
            w(f"| `{aid}` | {(notes[aid].get('title') or '').replace('|', '/')[:88]} |")
    else:
        w("None currently classified `yes`/`analysis` violate the three conditions.")

    w("")
    w("## Policy notes")
    w("")
    w("- V4 published text is never retro-edited; exclusions apply to V5 onward.")
    w("- Awesome README tracks method papers (`is_opd=yes`); analysis-only entries are excluded by policy.")
    w("- Gemini second-opinion REJECTs based on novelty/domain are **not** OPD criteria and must be re-checked against the three conditions.")

    (ROOT / "papers-meta/v5-integration-backlog.md").write_text("\n".join(out) + "\n")
    print(f"pending={len(pending)} ignored_tech={len(ignored)} rejected_3c={len(rejected_3c)}")


if __name__ == "__main__":
    main()
